version: 2
updates:
  
  # Maintains wally dependency
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  
  # Maintains workflow actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
